run:
  concurrency: 4
  timeout: 1m

linters-settings:
  tagalign:
    align: false
    sort: false
  govet:
    check-shadowing: true
    enable:
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - reflectvaluecompare
      - shadow
      - shift
      - sigchanyzer
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  wrapcheck:
    ignoreSigs:
      - httperror.New(
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - .WrapError(
    ignoreSigRegexps:
      - \.New.*Error\(
    ignorePackageGlobs:
      - encoding/*
      - github.com/pkg/*
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: var-naming
        severity: warning
      - name: var-declaration
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: errorf
        severity: warning
      - name: empty-block
        severity: warning
      - name: unused-parameter
        severity: warning
      - name: unreachable-code
        severity: warning
      - name: redefines-builtin-id
        severity: warning
      - name: superfluous-else
        severity: warning
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: blank-imports
        severity: warning
      - name: range
        severity: warning
      - name: time-naming
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: indent-error-flow
        severity: warning

linters:
  disable-all: true
  enable:
    - asciicheck 
    - durationcheck 
    - errcheck 
    - errorlint 
    - exhaustive 
    - gosec 
    - govet 
    - makezero 
    - nilerr 
    - exportloopref 
    - staticcheck 
    - typecheck 
    - bodyclose 
    - noctx 
    - prealloc
    - gosimple
    - ineffassign
    - unparam
    - unused
  presets:
    - comment 
    - error 
    - format 
    - metalinter 

issues:
  exclude-use-default: false